// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoe7_thjE2cUbQyIVaJF19ZXfpA8f-Qho',
    appId: '1:1051828684170:web:eba1aa3c6249c644f8f473',
    messagingSenderId: '1051828684170',
    projectId: 'goapp-a12ee',
    authDomain: 'goapp-a12ee.firebaseapp.com',
    storageBucket: 'goapp-a12ee.appspot.com',
    measurementId: 'G-PHVPG4ZLS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmihLmazyTrUxtLVEqYgdetj9vmU2-iXk',
    appId: '1:1051828684170:android:79e2fd61c91e3586f8f473',
    messagingSenderId: '1051828684170',
    projectId: 'goapp-a12ee',
    storageBucket: 'goapp-a12ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQFIKPMuTlmDcVtVt_ImvzQfvRgzmSmC0',
    appId: '1:1051828684170:ios:1f0132550f17bb77f8f473',
    messagingSenderId: '1051828684170',
    projectId: 'goapp-a12ee',
    storageBucket: 'goapp-a12ee.appspot.com',
    iosClientId: '1051828684170-kckl60b1ploj1srkc3rrre6g9jqpfpgc.apps.googleusercontent.com',
    iosBundleId: 'com.hero.go',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQFIKPMuTlmDcVtVt_ImvzQfvRgzmSmC0',
    appId: '1:1051828684170:ios:1f0132550f17bb77f8f473',
    messagingSenderId: '1051828684170',
    projectId: 'goapp-a12ee',
    storageBucket: 'goapp-a12ee.appspot.com',
    iosClientId: '1051828684170-kckl60b1ploj1srkc3rrre6g9jqpfpgc.apps.googleusercontent.com',
    iosBundleId: 'com.hero.go',
  );
}
